services:
  thesis-runner:
    build: . 
    privileged: true
    cap_add:
      - SYS_ADMIN
      - PERFMON
    security_opt:
      - seccomp:unconfined
    volumes:
      - /proc:/hostproc:ro
      - "./:/mnt/thesis-project"
    stdin_open: true
    tty: true
    command: /bin/bash  
