# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/Thesis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/Thesis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/Thesis/CMakeFiles /workspaces/Thesis//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/Thesis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named interop

# Build rule for target.
interop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 interop
.PHONY : interop

# fast build rule for target.
interop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/build
.PHONY : interop/fast

src/cpp/aabb.o: src/cpp/aabb.cpp.o
.PHONY : src/cpp/aabb.o

# target to build an object file
src/cpp/aabb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/aabb.cpp.o
.PHONY : src/cpp/aabb.cpp.o

src/cpp/aabb.i: src/cpp/aabb.cpp.i
.PHONY : src/cpp/aabb.i

# target to preprocess a source file
src/cpp/aabb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/aabb.cpp.i
.PHONY : src/cpp/aabb.cpp.i

src/cpp/aabb.s: src/cpp/aabb.cpp.s
.PHONY : src/cpp/aabb.s

# target to generate assembly for a file
src/cpp/aabb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/aabb.cpp.s
.PHONY : src/cpp/aabb.cpp.s

src/cpp/bvh.o: src/cpp/bvh.cpp.o
.PHONY : src/cpp/bvh.o

# target to build an object file
src/cpp/bvh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/bvh.cpp.o
.PHONY : src/cpp/bvh.cpp.o

src/cpp/bvh.i: src/cpp/bvh.cpp.i
.PHONY : src/cpp/bvh.i

# target to preprocess a source file
src/cpp/bvh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/bvh.cpp.i
.PHONY : src/cpp/bvh.cpp.i

src/cpp/bvh.s: src/cpp/bvh.cpp.s
.PHONY : src/cpp/bvh.s

# target to generate assembly for a file
src/cpp/bvh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/bvh.cpp.s
.PHONY : src/cpp/bvh.cpp.s

src/cpp/color.o: src/cpp/color.cpp.o
.PHONY : src/cpp/color.o

# target to build an object file
src/cpp/color.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/color.cpp.o
.PHONY : src/cpp/color.cpp.o

src/cpp/color.i: src/cpp/color.cpp.i
.PHONY : src/cpp/color.i

# target to preprocess a source file
src/cpp/color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/color.cpp.i
.PHONY : src/cpp/color.cpp.i

src/cpp/color.s: src/cpp/color.cpp.s
.PHONY : src/cpp/color.s

# target to generate assembly for a file
src/cpp/color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/color.cpp.s
.PHONY : src/cpp/color.cpp.s

src/cpp/hittable.o: src/cpp/hittable.cpp.o
.PHONY : src/cpp/hittable.o

# target to build an object file
src/cpp/hittable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/hittable.cpp.o
.PHONY : src/cpp/hittable.cpp.o

src/cpp/hittable.i: src/cpp/hittable.cpp.i
.PHONY : src/cpp/hittable.i

# target to preprocess a source file
src/cpp/hittable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/hittable.cpp.i
.PHONY : src/cpp/hittable.cpp.i

src/cpp/hittable.s: src/cpp/hittable.cpp.s
.PHONY : src/cpp/hittable.s

# target to generate assembly for a file
src/cpp/hittable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/hittable.cpp.s
.PHONY : src/cpp/hittable.cpp.s

src/cpp/main.o: src/cpp/main.cpp.o
.PHONY : src/cpp/main.o

# target to build an object file
src/cpp/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/main.cpp.o
.PHONY : src/cpp/main.cpp.o

src/cpp/main.i: src/cpp/main.cpp.i
.PHONY : src/cpp/main.i

# target to preprocess a source file
src/cpp/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/main.cpp.i
.PHONY : src/cpp/main.cpp.i

src/cpp/main.s: src/cpp/main.cpp.s
.PHONY : src/cpp/main.s

# target to generate assembly for a file
src/cpp/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/main.cpp.s
.PHONY : src/cpp/main.cpp.s

src/cpp/math_util.o: src/cpp/math_util.cpp.o
.PHONY : src/cpp/math_util.o

# target to build an object file
src/cpp/math_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/math_util.cpp.o
.PHONY : src/cpp/math_util.cpp.o

src/cpp/math_util.i: src/cpp/math_util.cpp.i
.PHONY : src/cpp/math_util.i

# target to preprocess a source file
src/cpp/math_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/math_util.cpp.i
.PHONY : src/cpp/math_util.cpp.i

src/cpp/math_util.s: src/cpp/math_util.cpp.s
.PHONY : src/cpp/math_util.s

# target to generate assembly for a file
src/cpp/math_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/math_util.cpp.s
.PHONY : src/cpp/math_util.cpp.s

src/cpp/sphere.o: src/cpp/sphere.cpp.o
.PHONY : src/cpp/sphere.o

# target to build an object file
src/cpp/sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/sphere.cpp.o
.PHONY : src/cpp/sphere.cpp.o

src/cpp/sphere.i: src/cpp/sphere.cpp.i
.PHONY : src/cpp/sphere.i

# target to preprocess a source file
src/cpp/sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/sphere.cpp.i
.PHONY : src/cpp/sphere.cpp.i

src/cpp/sphere.s: src/cpp/sphere.cpp.s
.PHONY : src/cpp/sphere.s

# target to generate assembly for a file
src/cpp/sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/sphere.cpp.s
.PHONY : src/cpp/sphere.cpp.s

src/cpp/triangle.o: src/cpp/triangle.cpp.o
.PHONY : src/cpp/triangle.o

# target to build an object file
src/cpp/triangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/triangle.cpp.o
.PHONY : src/cpp/triangle.cpp.o

src/cpp/triangle.i: src/cpp/triangle.cpp.i
.PHONY : src/cpp/triangle.i

# target to preprocess a source file
src/cpp/triangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/triangle.cpp.i
.PHONY : src/cpp/triangle.cpp.i

src/cpp/triangle.s: src/cpp/triangle.cpp.s
.PHONY : src/cpp/triangle.s

# target to generate assembly for a file
src/cpp/triangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/triangle.cpp.s
.PHONY : src/cpp/triangle.cpp.s

src/cpp/user_types.o: src/cpp/user_types.cpp.o
.PHONY : src/cpp/user_types.o

# target to build an object file
src/cpp/user_types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/user_types.cpp.o
.PHONY : src/cpp/user_types.cpp.o

src/cpp/user_types.i: src/cpp/user_types.cpp.i
.PHONY : src/cpp/user_types.i

# target to preprocess a source file
src/cpp/user_types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/user_types.cpp.i
.PHONY : src/cpp/user_types.cpp.i

src/cpp/user_types.s: src/cpp/user_types.cpp.s
.PHONY : src/cpp/user_types.s

# target to generate assembly for a file
src/cpp/user_types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interop.dir/build.make CMakeFiles/interop.dir/src/cpp/user_types.cpp.s
.PHONY : src/cpp/user_types.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... interop"
	@echo "... src/cpp/aabb.o"
	@echo "... src/cpp/aabb.i"
	@echo "... src/cpp/aabb.s"
	@echo "... src/cpp/bvh.o"
	@echo "... src/cpp/bvh.i"
	@echo "... src/cpp/bvh.s"
	@echo "... src/cpp/color.o"
	@echo "... src/cpp/color.i"
	@echo "... src/cpp/color.s"
	@echo "... src/cpp/hittable.o"
	@echo "... src/cpp/hittable.i"
	@echo "... src/cpp/hittable.s"
	@echo "... src/cpp/main.o"
	@echo "... src/cpp/main.i"
	@echo "... src/cpp/main.s"
	@echo "... src/cpp/math_util.o"
	@echo "... src/cpp/math_util.i"
	@echo "... src/cpp/math_util.s"
	@echo "... src/cpp/sphere.o"
	@echo "... src/cpp/sphere.i"
	@echo "... src/cpp/sphere.s"
	@echo "... src/cpp/triangle.o"
	@echo "... src/cpp/triangle.i"
	@echo "... src/cpp/triangle.s"
	@echo "... src/cpp/user_types.o"
	@echo "... src/cpp/user_types.i"
	@echo "... src/cpp/user_types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

