name = "juliaThesis"
uuid = "8f12cffc-3094-41db-83b0-e6c95e351162"
authors = ["KaiErikNiermann"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
