"""
This type stub file was generated by pyright.
"""

__version__ = ...
_newmodule = ...
def newmodule(name):
    "A new module with the given name."
    ...

_convert = ...
def convert(T, x):
    "Convert x to a Julia T."
    ...

def interactive(enable=...): # -> None:
    "Allow the Julia event loop to run in the background of the Python REPL."
    ...

class JuliaError(Exception):
    "An error arising in Julia code."
    def __init__(self, exception, backtrace=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    @property
    def exception(self): # -> Any:
        ...
    
    @property
    def backtrace(self): # -> Any:
        ...
    


CONFIG = ...
def init(): # -> None:
    ...

def load_ipython_extension(ip): # -> None:
    ...

