"""
This type stub file was generated by pyright.
"""

"""Experimental module for loading Julia files as Python modules.

Being experimental, it does not form part of the JuliaCall API. It may be changed or removed
in any release.

Basic usage is:
    import juliacall.importer
    juliacall.importer.install()

And now you can import any Julia file as Python module. That is, if 'foo.jl' is in your
Python path, then 'import foo' will work.

By default, all objects at the top level of the file whose name does not start with '_' are
exposed. Alternatively, you may explicitly 'export' objects.

The importer is intended for development use. To release a package, use 'gen_file' on each
Julia module file to generate a corresponding Python file and only include the Python files
in the release.
"""
from importlib.machinery import ModuleSpec
from typing import Optional

class Finder:
    def __init__(self, jlext=..., pyext=...) -> None: ...
    def find_spec(self, fullname, path, target=...) -> Optional[ModuleSpec]: ...

def install(**kw) -> Finder:
    """Install the Julia importer.

    After calling this, files ending '.jl' in your Python path may be imported as Python
    modules.

    The return value may be passed to 'uninstall'.
    """
    ...

def uninstall(finder) -> None:
    """Uninstall the Julia importer."""
    ...

def gen_code(jl) -> str: ...
def gen_file(jl, py) -> None:
    """Convert a Julia module file to a Python module file."""
    ...

def exec_module(name, code) -> None: ...
