"""
This type stub file was generated by pyright.
"""

from IPython.core.magic import Magics, line_cell_magic, magics_class

"""Experimental IPython extension for Julia.

Being experimental, it does not form part of the JuliaCall API. It may be changed or removed
in any release.

Enable the extension by calling the magic '%load_ext juliacall'.

Features:
- Magic `%julia code` to evaluate a piece of Julia code in-line.
- Cell magic `%%julia` to evaluate a cell of Julia code.
- Julia's stdin and stdout are redirected to Python's stdin and stdout.
- Calling Julia's 'display(x)' function will display 'x' in IPython.
"""
_set_var = ...
_get_var = ...
_egal = ...

@magics_class
class JuliaMagics(Magics):
    @line_cell_magic
    def julia(self, line, cell=...) -> None: ...

def load_ipython_extension(ip) -> None: ...
