"""
This type stub file was generated by pyright.
"""

from matplotlib.backend_bases import FigureManagerBase
from matplotlib.backends.backend_agg import FigureCanvasAgg

"""
Minimal matplotlib backend which shows plots using Julia's display mechanism.
"""
FigureCanvas = FigureCanvasAgg

def show(format=...) -> None: ...

FORMAT_TO_MIME = ...

class FigureManager(FigureManagerBase):
    def show(self, format=...) -> None: ...
