name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Julia
      uses: julia-actions/setup-julia@latest
      with:
        version: '1.10.2'

    - name: Activate Project Environment
      run: |
        julia --project=.

    - name: Install Dependencies
      run: |
        julia --project=. -e 'import Pkg; Pkg.instantiate()'

    - name: Run Tests
      run: |
        julia --project=. -e 'import Pkg; Pkg.test()'
